### Get all spaces
GET {{host}}/api/v1/spaces HTTP/1.1

### Get by id
GET {{host}}/api/v1/spaces/64c684c9740674e92952307e HTTP/1.1




### Get by id children
GET {{host}}/api/v1/spaces/with-pagination HTTP/1.1




### GET DESCENDANTS
GET {{host}}/api/v1/spaces/descendants/6432ced15647e578ce20f8a0 HTTP/1.1


### GET HEAD TO TAIL
GET {{host}}/api/v1/spaces/head-to-tail/6432ced15647e578ce20f8a0 HTTP/1.1
###
GET {{host}}/api/v1/spaces/descendants/643392f31265c1756e6bdcb7 HTTP/1.1


### condo sato srl
GET {{host}}/api/v1/organizations/643861526aec086124b0e0e7 HTTP/1.1

### SELECTED ORGANIZATION AT HEADER
GET {{host}}/api/v1/organizations/selected/643861526aec086124b0e0e7 HTTP/1.1

### 

GET {{host}}/api/v1/spaces/static-props/a HTTP/1.1
### 

GET {{host}}/api/v/spaces/static-props/a HTTP/1.1
### 

GET {{host}}/api/v1/spaces/ho HTTP/1.1
###
GET {{host}}/api/v1/spaces/static-props/contardo-ferrini--condominio?ssg_secret={{ssg_secret}} HTTP/1.1