# ADMIN 
POST {{host}}/api/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "{{user}}",
  "password": "{{password}}"
}

###
POST {{host}}/api/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "{{superAdminEmail}}",
  "password": "{{password}}"
}
###
POST {{host}}/api/v1/auth/login HTTP/1.1
content-type: application/json

{
  "email": "contardo@admin.com",
  "password": "{{password}}"
}
###
GET {{host}}/api/v1/auth/me HTTP/1.1